<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class CronReport extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // is_login();
        date_default_timezone_set('Asia/Jakarta');
        $this->load->model('Send_message_detail_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
        $this->config->load('apiwha');

        $this->apiToken     = "2iNvy9zUUVSwMXSO71SIvdNwjE2c7DrfV6Kn3tCRcOvrkMnvl74kraCUbhZAHZZO";
        // $this->wablasClient = new WablasClient($apiToken);
        $this->url          = 'https://wablas.com/api';
        $this->client       = new GuzzleHttp\Client();
        $this->startRes = time();

    }

    public function index()
    {

    } 
    
    public function today() {
        $curl = curl_init();
        $token = "2iNvy9zUUVSwMXSO71SIvdNwjE2c7DrfV6Kn3tCRcOvrkMnvl74kraCUbhZAHZZO";

        curl_setopt($curl, CURLOPT_HTTPHEADER,
            array(
                "Authorization: $token",
            )
        );
        $date = date("Y-m-d");
        $url  = "https://wablas.com/api/report?from=".$date."&to=".$date;
        // echo $date;die();
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, 0);
        $result = curl_exec($curl);
        curl_close($curl);

        echo "<pre>";
        print_r($result);
        $objResult = json_decode($result);
        foreach ($objResult->data as $key => $value) {
            // echo print_r($value);
            $row = $this->Send_message_detail_model->get_by_msg_id($value->id);
            if ($row) {
                $whereArr = [
                    "message_id" => $value->id
                ];
                $dataUPdate = [
                    "status" => $value->status
                ];

                 $this->Send_message_detail_model->updateWhere($dataUPdate,$whereArr);
            }
        }

        $this->Loging("Report" , $result);
    }

    function Loging($name,$param){

      $fullpath=FCPATH.'Log/'.date('Y').'/'.date('m').'/'.date('d');
      $filepath = $fullpath.'/'.$name.'.txt';
      if (!is_dir($fullpath)) {
        mkdir($fullpath, 0755, TRUE);
      }
      $saveData = [
        "timeRes" => time() - $this->startRes,
        "param" => $param
      ];

      file_put_contents($filepath,json_encode($saveData).PHP_EOL, FILE_APPEND);
    }

    public function read($id) 
    {
        $row = $this->Send_message_detail_model->get_by_id($id);
        if ($row) {
            echo json_encode([
                "code" => "success",
                "message" => "Record Found",
                "data" => $row,
            ]);die();
        } else {
            echo json_encode([
                "code" => "error",
                "message" => "Record Not Found",
            ]);die();
        }
    }

}

/* End of file Send_message.php */
/* Location: ./application/controllers/Send_message.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-08 15:45:08 */
/* http://harviacode.com */