<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');



class Guzzle extends CI_Controller
{
    protected $recipients = [];

    function __construct()
    {
        parent::__construct();
        is_login();
        $this->apiToken     = "2iNvy9zUUVSwMXSO71SIvdNwjE2c7DrfV6Kn3tCRcOvrkMnvl74kraCUbhZAHZZO";
        // $this->wablasClient = new WablasClient($apiToken);
        $this->url          = 'https://wablas.com/api';
        $this->client       = new GuzzleHttp\Client();

    }

    public function index()
    {
        // add recipient (support multiple recipient)
        $this->addRecipient('6282125252292');
        $this->addRecipient('6285693784939');
        // $this->addRecipient('6281288204242');

        // send message
        $message = 'Ini adalah pesan dari wablas \n harap jangan di balas';
        // echo print_r($this->recipients);
         
        $this->sendMessage($message);
        // $this->template->load('template','user/tbl_user_list');
    } 

    public function sendMessage($message, $type = 'random') {
       
       try {
            # guzzle post request example with form parameter
            // $this->client->setDefaultOption('headers', [
            //                                                     'Accept' => 'application/json',
            //                                                     'Authorization' => $this->apiToken,
            //                                                 ]);
            $response = $this->client->request( 'POST', 
                                           $this->url."/send-message", 
                                           // [
                                           //  'headers' => [
                                           //                      'Accept' => 'application/json',
                                           //                      'Authorization' => $this->apiToken,
                                           //                  ]
                                           // ],
                                          [ 
                                            'headers' => [
                                                                'Accept' => 'application/json',
                                                                'Authorization' => $this->apiToken,
                                                            ],
                                            'form_params' 
                                                => [
                                                // 'phone'     => '6285693784939',
                                                'phone'     => implode(", ", $this->recipients),
                                                'message'   => $message,
                                                'type'      => $type
                                            ] 
                                          ]
                                        );
            #guzzle repose for future use
            $status_code = $response->getStatusCode(); // 200
            // echo $response->getReasonPhrase(); // OK
            // echo $response->getProtocolVersion(); // 1.1
            $body =  json_decode($response->getBody(),true);
            echo json_encode($body);
          } catch (GuzzleHttp\Exception\BadResponseException $e) {
            #guzzle repose for future use
            $response = $e->getResponse();
            $responseBodyAsString = $response->getBody()->getContents();
            print_r($responseBodyAsString);
          }

        return false    ;
    }

    public function addRecipient($phoneNumber) {
        $this->recipients[] = $phoneNumber;
    }
    

}

/* End of file User.php */
/* Location: ./application/controllers/User.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 06:32:22 */
/* http://harviacode.com */