<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class ManageAllHotline extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        date_default_timezone_set('Asia/Jakarta');
        $this->load->model('ManageAllHotline_model');
        $this->load->library('form_validation');
	    $this->load->library('datatables');
    }

    public function index()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('milis_member/create_action'),
            'id' => set_value(''),
            'milis_id' => set_value(''),
            'user_id' => set_value(''),
            'created' => set_value(''),
            'createdby' => set_value(''),
            'updated' => set_value(''),
            'updatedby' => set_value(''),
        );
        $this->template->load('template','milis_member/milis_member_list', $data);
    } 

    /*------------------------ OPEN MEMBER---------------------------------------------------*/

    public function member($id)
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('manageallhotline/create_member'),
            'id' => set_value(''),
            'hotline_id' => set_value(''),
            'user_id' => set_value(''),
            'created' => set_value(''),
            'createdby' => set_value(''),
            'updated' => set_value(''),
            'updatedby' => set_value(''),
            'hotlineid' => $id,
        );
        $this->template->load('template','manageallhotline/manageallhotline_member_list', $data);
    } 
    
    public function member_json($hotline_id = "") {
        header('Content-Type: application/json');
        echo $this->ManageAllHotline_model->member_json($hotline_id);
    }

    /*------------------------ CLOSE MEMBER---------------------------------------------------*/
    /*------------------------ OPEN INBOX---------------------------------------------------*/

    public function inbox($id)
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('manageallhotline/create_inbox'),
            'id' => set_value(''),
            'message_id' => set_value(''),
            'fromMe' => set_value(''),
            'pushName' => set_value(''),
            'phone' => set_value(''),
            'message' => set_value(''),
            'timestamp' => set_value(''),
            'receiver' => set_value(''),
            'groupId' => set_value(''),
            'hotlineid' => $id,
        );
        $this->template->load('template','manageallhotline/manageallhotline_inbox_list', $data);
    } 
    
    public function inbox_json($hotline_id = "") {
        header('Content-Type: application/json');
        echo $this->ManageAllHotline_model->inbox_json($hotline_id);
    }

    /*------------------------ CLOSE INBOX---------------------------------------------------*/
    /*------------------------ OPEN OUTBOX---------------------------------------------------*/

    public function outbox($id)
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('manageallhotline/create_inbox'),
            'id' => set_value(''),
            'message_id' => set_value(''),
            'fromMe' => set_value(''),
            'pushName' => set_value(''),
            'phone' => set_value(''),
            'message' => set_value(''),
            'timestamp' => set_value(''),
            'receiver' => set_value(''),
            'groupId' => set_value(''),
            'hotlineid' => $id,
        );
        $this->template->load('template','manageallhotline/manageallhotline_inbox_list', $data);
    } 
    
    public function outbox_json($hotline_id = "") {
        header('Content-Type: application/json');
        echo $this->ManageAllHotline_model->inbox_json($hotline_id);
    }

    public function user($milis_id) {
        header('Content-Type: application/json');
        $dataMilis = $this->getUserMilis($milis_id);
        // echo print_r($dataMilis);
        // die;
        echo $this->User_model->jsonMember($dataMilis);
    }


    public function _rules() 
    {
	$this->form_validation->set_rules('milis_id', 'milis id', 'trim|required');
	$this->form_validation->set_rules('user_id', 'contact admin', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Milis_member.php */
/* Location: ./application/controllers/Milis_member.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-14 12:19:40 */
/* http://harviacode.com */