<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');
use wablas\wablasclientphp\src\WablasClient;

use GuzzleHttp\Client as GuzzleClient;
use GuzzleHttp\RequestOptions;


class TestSend extends CI_Controller
{
    protected $wablasEndpoint = 'https://wablas.com/api';
    protected $apiToken;
    protected $recipients = [];
    protected $httpClient;
    protected $headers;
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('API/User_model');
        $this->load->library('form_validation');        
        $this->load->library('datatables');
        $apiToken = "2iNvy9zUUVSwMXSO71SIvdNwjE2c7DrfV6Kn3tCRcOvrkMnvl74kraCUbhZAHZZO";
        // $this->wablasClient = new WablasClient($apiToken);

        $this->apiToken = $apiToken;
        $this->headers = [
            'Accept' => 'application/json',
            'Authorization' => $this->apiToken,
        ];

        $this->httpClient = new GuzzleClient([
            'base_uri' => $this->wablasEndpoint
        ]);

    }

    public function index()
    {
        echo "12321312";
        // add recipient (support multiple recipient)
        $this->addRecipient('6285693784939');

        // send message
        $message = 'type your message here.';
        echo print_r($this->recipients);
        // $this->sendMessage($message);
        // $this->template->load('template','user/tbl_user_list');
    } 

    public function addRecipient($phoneNumber) {
        $this->recipients[] = $phoneNumber;
    }

    public function sendMessage($message, $type = 'random') {
        if (!empty($this->recipients)) {
            $res = $this->httpClient->post('/send-message', [
                RequestOptions::HEADERS => $this->headers,
                RequestOptions::FORM_PARAMS => [
                    'phone'     => implode(", ", $this->recipients),
                    'message'   => $message,
                    'type'      => $type
                ],
            ]); 

            return $res->getBody();
        }
       

        return false;
    }
    

}

/* End of file User.php */
/* Location: ./application/controllers/User.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 06:32:22 */
/* http://harviacode.com */