<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class ManageInvoice_model extends CI_Model
{

    public $table = 'tbl_invoice';
    public $table2 = 'milis';
    public $table3 = 'tbl_package';
    public $id = 'invoice_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.invoice_id,b.name,a.invoice_number,c.package_name,c.package_price,a.invoice_status,a.invoice_start_date,a.invoice_end_date,a.created,a.createdby,a.updated,a.updatedby');
        $this->datatables->from('tbl_invoice a');
        //add this line for join
        $this->datatables->join('milis b', 'b.id = a.milis_id');
        $this->datatables->join('tbl_package c', 'c.package_id = a.invoice_package');
        $this->datatables->add_column('action', '<a href="#" class="btn btn-danger btn-sm" onclick="editModal($1);return false;"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>  <a href="#" class="btn btn-danger btn-sm" onclick="delete_conf($1);return false;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>', 'package_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('invoice_id', $q);
	$this->db->or_like('milis_id', $q);
	$this->db->or_like('invoice_number', $q);
	$this->db->or_like('invoice_package', $q);
	$this->db->or_like('invoice_start_date', $q);
	$this->db->or_like('invoice_end_date', $q);
	$this->db->or_like('invoice_status', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('createdby', $q);
	$this->db->or_like('updated', $q);
	$this->db->or_like('updatedby', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('invoice_id', $q);
	$this->db->or_like('milis_id', $q);
	$this->db->or_like('invoice_number', $q);
	$this->db->or_like('invoice_package', $q);
	$this->db->or_like('invoice_start_date', $q);
	$this->db->or_like('invoice_end_date', $q);
	$this->db->or_like('invoice_status', $q);
	$this->db->or_like('created', $q);
	$this->db->or_like('createdby', $q);
	$this->db->or_like('updated', $q);
	$this->db->or_like('updatedby', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file ManageInvoice_model.php */
/* Location: ./application/models/ManageInvoice_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-15 17:31:31 */
/* http://harviacode.com */