<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Send_message_detail_model extends CI_Model
{

    public $table = 'send_message_detail';
    public $table_header = 'send_message_header';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('pid as id,pid,header_pid,from_num,dest_num,message_id,message_text,status,created,createdby,updated,updatedby');
        $this->datatables->from($this->table);
        //add this line for join
        //$this->datatables->join('table2', 'send_message_detail.field = table2.field');
        $this->datatables->add_column('action', '<a href="#" class="btn btn-danger btn-sm" onclick="editModal($1);return false;"><i class="fa fa-eye" aria-hidden="true"></i> </a>', 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get data by id
    function get_by_msg_id($id)
    {
        $this->db->where('message_id', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('header_id', $q);
    	$this->db->or_like('from_num', $q);
    	$this->db->or_like('dest_num', $q);
    	$this->db->or_like('message_id', $q);
    	$this->db->or_like('message_text', $q);
    	$this->db->or_like('status', $q);
    	$this->db->or_like('created', $q);
    	$this->db->or_like('createdby', $q);
    	$this->db->or_like('updated', $q);
    	$this->db->or_like('updatedby', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('header_id', $q);
    	$this->db->or_like('from_num', $q);
    	$this->db->or_like('dest_num', $q);
    	$this->db->or_like('message_id', $q);
    	$this->db->or_like('message_text', $q);
    	$this->db->or_like('status', $q);
    	$this->db->or_like('created', $q);
    	$this->db->or_like('createdby', $q);
    	$this->db->or_like('updated', $q);
    	$this->db->or_like('updatedby', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    function get_header_table(){
        return $this->table_header;
    }

    function set_header_table($name){
        $this->table_header = $name;
    }

    function get_table(){
        return $this->table;
    }

    function set_table($name){
        $this->table = $name;
    }

    // insert data header
    function insert_header($data)
    {
        $this->db->insert($this->table_header, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update data
    function updateWhere($data, $where)
    {
        $this->db->where($where);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Send_message_detail_model.php */
/* Location: ./application/models/Send_message_detail_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-08 15:45:08 */
/* http://harviacode.com */