<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Company_model extends CI_Model
{

    public $table = 'ms_company';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        $this->db = $this->load->database('server_admin', TRUE);
    }


    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    // get data by id
    function get_by_where($where)
    {
        $this->db->where($where);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
    	$this->db->or_like('full_name', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('password', $q);
    	$this->db->or_like('images', $q);
    	$this->db->or_like('id_user_level', $q);
    	$this->db->or_like('is_aktif', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
    	$this->db->or_like('full_name', $q);
    	$this->db->or_like('email', $q);
    	$this->db->or_like('password', $q);
    	$this->db->or_like('images', $q);
    	$this->db->or_like('id_user_level', $q);
    	$this->db->or_like('is_aktif', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }


    // update data
    function updateWhere($where, $data)
    {

        $this->db->select('*');
        $this->db->where($where);//you can use another field
        $dataCompany = $this->db->get($this->table)->row();
        if (!$dataCompany) {
            $query = $this->db->insert($this->table, $data);//insert data
        } else {
            $data = [
                "name_replace" => $data['name_replace']
            ];
            $this->db->where($where);
            $this->db->update($this->table, $data);
        }
    }
    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User_model.php */
/* Location: ./application/models/User_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-04 06:32:22 */
/* http://harviacode.com */