<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class ManageContact_model extends CI_Model
{

    public $tbl_contact     = 'mst_contact';
    public $tbl_contact_id  = 'id';
    public $order           = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id, name_wa, name_replace, phone, group_hotline,created,createdby,updated,updatedby');
        $this->datatables->from($this->tbl_contact);
        //add this line for join
        //$this->datatables->join('table2', 'milis.field = table2.field');
        $this->datatables->add_column('action', '<a href="#" class="btn btn-danger btn-sm" onclick="editModal($1);return false;"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> </a>  <a href="#" class="btn btn-danger btn-sm" onclick="delete_conf($1);return false;"><i class="fa fa-trash-o" aria-hidden="true"></i></a>', 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->tbl_contact)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->tbl_contact_id, $id);
        return $this->db->get($this->tbl_contact)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like($this->tbl_contact_id, $q);
        $this->db->or_like('name_wa', $q);
        $this->db->or_like('name_replace', $q);
        $this->db->or_like('phone', $q);
        $this->db->or_like('group_hotline', $q);
        $this->db->or_like('created', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updated', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->from($this->tbl_contact);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like($this->tbl_contact_id, $q);
        $this->db->or_like('name_wa', $q);
        $this->db->or_like('name_replace', $q);
        $this->db->or_like('phone', $q);
        $this->db->or_like('group_hotline', $q);
        $this->db->or_like('created', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updated', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->tbl_contact)->result();
    }

    // insert data
    function insert($data)
    {
        try{
            $this->db->insert($this->tbl_contact, $data);
            return true;
        }catch(Exception $e){
            return false;
        }
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->tbl_contact_id, $id);
        $this->db->update($this->tbl_contact, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->tbl_contact_id, $id);
        $this->db->delete($this->tbl_contact);
    }

}

/* End of file ManagePackage_model.php */
/* Location: ./application/models/ManagePackage_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-09-15 17:32:53 */
/* http://harviacode.com */