<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class DirectLink extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // is_login();
        date_default_timezone_set('Asia/Jakarta');

        $this->config->load('apiwha');
        $this->load->library('directlinklib');
        $this->load->model('Contact_model');

    }
 
    public function index()
    {
        echo "43312";
    } 

    public function create_link(){
      $link = $this->input->post('link',TRUE);

      $this->directlinklib->urlTarget = base_url("API/DirectLink/file");
      $urlGenerate = $this->directlinklib->create_link($link);

      echo "<br>\n";
      echo ($urlGenerate);
      // if (condition) {
      //   # code...
      // }

    }

    public function file($document , $filename){
      if ($document == "image") {
          header("Content-type: image/jpeg");
          header("Content-Disposition: inline; filename=filename.jpeg");
          @readfile($this->config->item('webServer').$document."/".$filename);
      } else {
        // echo  print_r(["document" =>$document , "filename"=>$filename]);

        header("Content-type: application");
        // header("Content-Disposition: inline; filename=filename.pdf");
        @readfile($this->config->item('webServer').$document."/".$filename);
        // echo '<iframe src="'.$this->config->item('webServer').$document."/".$filename.'"></iframe>';
      }

      // echo $this->config->item('webServer').$document."/".$filename;
      // echo  print_r(["document" =>$document , "filename"=>$filename]);
      // echo  print_r(["document" =>$document , "filename"=>$filename]);
    }

    function Loging($name,$param){

      $fullpath=FCPATH.'Log/'.date('Y').'/'.date('m').'/'.date('d');
      $filepath = $fullpath.'/'.$name.'.txt';
      if (!is_dir($fullpath)) {
        mkdir($fullpath, 0755, TRUE);
      }
      $saveData = [
        "timeRes" => time() - $this->startRes,
        "param" => $param
      ];

      file_put_contents($filepath,json_encode($saveData).PHP_EOL, FILE_APPEND);
    }

}

/* End of file Hotline.php */
/* Location: ./application/controllers/Hotline.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-15 11:41:24 */
/* http://harviacode.com */