<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');


use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version1X;

class Notification extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // is_login();
        
        date_default_timezone_set('Asia/Jakarta');
        $this->load->model('Send_message_detail_model');
        $this->load->library('form_validation');        
        $this->load->library('datatables');
        $this->config->load('apiwha');
        $this->config->load('companyProfile');
        $this->load->model('Inbox_model');
        $this->load->model('Milis_model');
        $this->load->model('Notification_model');

        // $this->apiToken     = "2iNvy9zUUVSwMXSO71SIvdNwjE2c7DrfV6Kn3tCRcOvrkMnvl74kraCUbhZAHZZO";
        // $this->wablasClient = new WablasClient($apiToken);
        $this->apiToken     = "";
        $this->url          = $this->config->item('APIWeb');
        $this->client       = new GuzzleHttp\Client();
        $this->load->model('Milis_member_model');
        $this->load->model('Hotline_model');
        $this->load->model('Contact_model');
        $this->startRes = time();

    }

    public function index()
    {
        header('Content-Type: application/json');
        echo json_encode($this->Notification_model->get_all());
    } 

    public function hotline($number)
    {
        header('Content-Type: application/json');
        echo json_encode($this->Notification_model->get_all_where(['group_hotline' => $number]));
    } 
    // public function hotline($number)
    // {
    //     echo "Hotline".$number;
    // } 

    function Loging($name,$param){

      $fullpath=FCPATH.'Log/'.date('Y').'/'.date('m').'/'.date('d');
      $filepath = $fullpath.'/'.$name.'.txt';
      if (!is_dir($fullpath)) {
        mkdir($fullpath, 0755, TRUE);
      }
      $saveData = [
        "timeRes" => time() - $this->startRes,
        "param" => $param
      ];

      file_put_contents($filepath,json_encode($saveData).PHP_EOL, FILE_APPEND);
    }


}

/* End of file Send_message.php */
/* Location: ./application/controllers/Send_message.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-08 15:45:08 */
/* http://harviacode.com */